variable "nv_vpc1_cidr" {}
variable "nv_vpc1" {}
variable "nv_owner" {}
variable "nv_vpc2_cidr" {}
variable "nv_vpc2" {}
variable "nv1_owner" {}
variable "ohio_vpc1_cidr" {}
variable "ohio_vpc1" {}
variable "ohio_owner" {}
variable "ohio_vpc2_cidr" {}
variable "ohio_vpc2" {}
variable "ohio1_owner" {}
variable "public_subnet1_cidr" {}
variable "public_subnet2_cidr" {}
variable "public_subnet3_cidr" {}
variable "public_subnet1_name" {}
variable "public_subnet2_name" {}
variable "public_subnet3_name" {}
